from django.db import migrations, models
import django.db.models.deletion
import django.core.validators

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Linea', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('codigo', models.CharField(max_length=20, unique=True)), ('nombre', models.CharField(max_length=100, unique=True)), ('activa', models.BooleanField(default=True)), ('head_count', models.PositiveIntegerField(default=2)), ('capacidad_hora', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]))], options={'ordering': ('codigo',)}),
        migrations.CreateModel(name='SKU', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('codigo', models.CharField(max_length=30, unique=True)), ('nombre', models.CharField(max_length=150)), ('familia', models.CharField(choices=[('SALSA','Salsa'),('ADEREZO','Aderezo'),('CONSERVA','Conserva')], max_length=20)), ('formato', models.CharField(max_length=50)), ('sabor', models.CharField(max_length=60)), ('contiene_alergeno', models.BooleanField(default=False)), ('unidad', models.CharField(default='unid', max_length=20))], options={'ordering': ('familia','formato','nombre')}),
        migrations.CreateModel(name='Turno', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nombre', models.CharField(max_length=80, unique=True)), ('hora_inicio', models.TimeField()), ('hora_fin', models.TimeField())], options={'ordering': ('hora_inicio',)}),
        migrations.CreateModel(name='Operario', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('codigo', models.CharField(max_length=30, unique=True)), ('nombres', models.CharField(max_length=120)), ('activo', models.BooleanField(default=True)), ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operarios', to='produccion.turno'))], options={'ordering': ('codigo',)}),
        migrations.CreateModel(name='SKULinea', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('velocidad_unidades_hora', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])), ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus_compatibles', to='produccion.linea')), ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_compatibles', to='produccion.sku'))]),
        migrations.CreateModel(name='OrdenFabricacion', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('numero', models.CharField(max_length=40, unique=True)), ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])), ('prioridad', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])), ('fecha_liberacion', models.DateTimeField()), ('fecha_compromiso', models.DateTimeField()), ('inicio_opt', models.DateTimeField(blank=True, null=True)), ('fin_opt', models.DateTimeField(blank=True, null=True)), ('inicio_real', models.DateTimeField(blank=True, null=True)), ('fin_real', models.DateTimeField(blank=True, null=True)), ('atraso_horas', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])), ('estado', models.CharField(choices=[('PENDIENTE','Pendiente'),('PROGRAMADA','Programada'),('RETRASADA','Retrasada'),('NO_FACTIBLE','No factible'),('EN_PROCESO','En proceso'),('FINALIZADA','Finalizada')], default='PENDIENTE', max_length=20)), ('motivo', models.TextField(blank=True)), ('linea_opt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_opt', to='produccion.linea')), ('linea_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_real', to='produccion.linea')), ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.sku'))], options={'ordering': ('fecha_compromiso','-prioridad')}),
        migrations.AddConstraint(model_name='skulinea', constraint=models.UniqueConstraint(fields=('sku','linea'), name='uq_sku_linea')),
    ]
